### ISSUE TITLE
disconnect at rename account

### ISSUE THREAD

**Issue by cleanrock** [lunixbochs/uberserver#11]
While testing flobby I noticed that the client is not disconnected when accounts are renamed (Dispatcher.finishRemove is badly broken).
See https://github.com/cleanrock/uberserver/commit/61c2afa4bb73f16fb44e41211960bb7558e38b21 for fix.

**Comment by lunixbochs** [comment]
This is fixed in 4ddfe4a6a8e148d77b1948736094a6a91f556ec0
Thanks.
