### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by abma** [lunixbochs/uberserver#17]
there is no license info in the repo...

**Comment by abma** [comment]
because of ip2country.py i would say gpl2+ makes sense...

**Comment by lunixbochs** [comment]
the repository has zero gpl code in it, and zero required to run.

**Comment by lunixbochs** [comment]
I'd probably go with WTF/PD.

**Comment by abma** [comment]
currently maybe yes, but it had gpl code inside it:

https://github.com/lunixbochs/uberserver/commit/8e48e314af4ac5b9a79f98f213339af85a23f962#L4R1

WTF/PD is http://en.wikipedia.org/wiki/WTFPL ?

**Comment by lunixbochs** [comment]
GPL is incompatible with revision control?

**Comment by lunixbochs** [comment]
http://www.gnu.org/licenses/gpl-faq.html#CombinePublicDomainWithGPL

**Comment by abma** [comment]
you mean github? afaik as long its opensource it should be fine

**Comment by lunixbochs** [comment]
I just said "WTF/PD"

**Comment by lunixbochs** [comment]
I didn't mean github. I said "my codebase has no GPL code in it" and you said "but there was some in the revision history" ;)

**Comment by abma** [comment]
what does "WTF/PD" mean?

yeah, i don't know what happened with the GPL'ed code, you've to know :) gpl was just a suggestion.

**Comment by lunixbochs** [comment]
wtfpl and public domain are two valid licenses.

**Comment by abma** [comment]
aaaah, ok. then choose please ;) i thought you mean a single license, not two.

**Comment by lunixbochs** [comment]
public domain is fine.

**Comment by lunixbochs** [comment]
I've properly licensed this as MIT.
