### ISSUE TITLE
hole punching doesn't work in midgame join

### ISSUE THREAD

**Issue by abma** [lunixbochs/uberserver#2]
looks like it is done only on game start, it should be done on rejoin, too.

(i'm unsure if this is a problem by lobby, engine or autohost...)

**Comment by lunixbochs** [comment]
host is notified of client's udp port via CLIENTIPPORT on battle join, and again if we receive a new UDP packet after battle join

looks like this is an issue in Spring (can autohost interface add UDP ports for new spectators?) and the lobby (if so, the lobby needs to support it)
