### ISSUE TITLE
Channel count mismatch

### ISSUE THREAD

**Issue by renefritze** [lunixbochs/uberserver#9]
It seems uberserver reports about 1.5 times the number of channels in its motd compared to the number one gets via the channellist command.

**Comment by lunixbochs** [comment]
doesn't report private channels in the list

## 

Ryan Hileman

**Comment by renefritze** [comment]
private channels == private messages or passworded channels?

**Comment by lunixbochs** [comment]
private messages are stateless - just delivered to their recipient and forgotten.

private channel right now = password or no owner:
https://github.com/lunixbochs/uberserver/blob/master/Protocol.py#L1830
